### ISSUE TITLE
Possible to have File Browser remember state as it used to?

### ISSUE THREAD

**Issue by Ben-Fenner** [tudo75/xed-restore-tabs-plugin#2]
Thank you so much for porting over this feature to xed.
I've tried it out a bit and it's obviously very helpful, but I noticed one improvement that could help.

When I'm working in my code repository, I have a few reference files open in xed from my Desktop, and then I have my code files open in tabs after those. In the File Browser I'm navigating my code repositories only, and I'm nowhere near the Desktop directory.
So when I close xed I have a few tabs open with files from my Desktop, then many files after that from my repositories and the File Browser is navigating my code repositories.
When I open xed back up, all of the file tabs are restored in their correct order, but because the first tab is a file from my Desktop, then File Browser opens up to the Desktop directory instead of where I had it before. This is new behavior. This takes a bit to navigate back to my code repositories, and it would be wonderful if I did not have to do that.

Interestingly enough, the session saver feature you ported over a year ago doesn't suffer from this problem. xed opens up as normal, with the File Browser remembering the last state it was in. Then the session is restored, and the File Browser remains as-is. It's just now that I'm seeing this File Browser behavior changing. I wonder if it could be corrected, to just remain as it was, not change to the location of the first file tab.

**Comment by tudo75** [comment]
Fixed. The new behaviour was due to the different times when files are loaded. Restore Tabs load them when Xed is opening while Session Saver after load it's completed, and the file Browser plugin default behaviour it's to load with the root folder of the first file opened as per schema:
```
<schema id="org.x.editor.plugins.filebrowser" path="/org/x/editor/plugins/filebrowser/">
    <key name="open-at-first-doc" type="b">
      <default>true</default>
      <summary>Set Location to First Document</summary>
      <description>If TRUE the file browser plugin will view the directory of the first opened document given that the file browser hasn't been used yet. (Thus this generally applies to opening a document from the command line or opening it with Caja, etc.)</description>
    </key>
```
I solved disabling before the load of the file and restoring the default after process is ended.

Bye

**Comment by Ben-Fenner** [comment]
You are a legend! Thank you so much! :hugs:
