### ISSUE TITLE
Solved

### ISSUE THREAD

**Issue by lowendgamer** [tudo75/xed-restore-tabs-plugin#3]
_Solved_

**Comment by tudo75** [comment]
Hi,
I suppose you're new to git. 
You must clone locally the repository:
`git clone https://github.com/tudo75/xed-restore-tabs-plugin.git`
and after that you have a folder called xed-restore-tabs-plugin. You must enter it with
`cd xed-restore-tabs-plugin`
and from here you must follow the install instructions
I've updated the install commands in the readme
Hope you'll find this plugin useful

**Comment by lowendgamer** [comment]
> Hi, I suppose you're new to git. You must clone locally the repository: `git clone https://github.com/tudo75/xed-restore-tabs-plugin.git` and after that you have a folder called xed-restore-tabs-plugin. You must enter it with `cd xed-restore-tabs-plugin` and from here you must follow the install instructions I've updated the install commands in the readme Hope you'll find this plugin useful

Thanks for that, I had no idea. I got an [error](https://i.imgur.com/wfQKY1F.png) after entering: `meson setup build --prefix=/usr`

**Comment by tudo75** [comment]
You need to install libgtksourceview-4-dev
`sudo apt install libgtksourceview-4-dev`

**Comment by lowendgamer** [comment]
> You need to install libgtksourceview-4-dev `sudo apt install libgtksourceview-4-dev`

Thank you so much for bearing with me. You are the best!
